# -*- coding: utf-8 -*-
"""markup_y.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dV7y8MPfaYnZe0kwcFXChuCE4LQyDjmt
"""

import datetime as dt
import pandas as pd
#from pandas_datareader import data as pdr
import matplotlib.pyplot as plt


## Размечаем Y

#from pandas_datareader import data as pdr 
#import datetime as dt


def SELL(data, counter_lvl, plotting):
    
    signals = pd.DataFrame() # dataframe для записи сигналов

    #df['High'].plot(label='high')
    if plotting == True:
        plt.figure(figsize=(22, 8))
        data['Close'].plot(label='close')
        
    pivots =[]
    dates = []
    counter = 0
    lastPivot = 0
    Range = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    daterange = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        
    for i in data.index:
        currentMax = max(Range , default=0)
        #value=round(df["High"][i],2)
        value=data['Close'][i]
            
        Range=Range[1:19]
        Range.append(value)
        daterange=daterange[1:19]
        daterange.append(i)
            
        if currentMax == max(Range , default=0):
            counter+=1
        else:
            counter = 0
        if counter ==  counter_lvl:
            lastPivot = currentMax
            dateloc = Range.index(lastPivot)
            lastDate = daterange[dateloc]
            pivots.append(lastPivot)
            dates.append(lastDate)
    print()
    #timeD = dt.timedelta(days=500)

    for index in range(1, len(pivots)):
        #print(str(pivots[index]) + " :" + str(dates[index]))
        line = pd.DataFrame({'Date':[dates[index]], 'price':[pivots[index]], 'Signal':[-1]})
        signals = signals.append(line, ignore_index=True)

        #plt.plot_date([dates[index], dates[index] + timeD],
        #    [pivots[index], pivots[index]] , linestyle='solid' , linewidth=1, marker=',', color='red')

        if plotting == True:
            plt.plot_date([dates[index], dates[index]],
            [pivots[index], pivots[index]], marker='v', color='red')

    if plotting == True:
        plt.grid()
        plt.show()

    return signals
    


def BUY(data, counter_lvl, plotting):
    
    signals = pd.DataFrame() # dataframe для записи сигналов

    #df['Low'].plot(label='low')
    if plotting == True:
        plt.figure(figsize=(22, 8))
        data['Close'].plot(label='close')
        
    pivots =[]
    dates = []
    counter = 0
    lastPivot = 0
    Range = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    daterange = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        
    for i in data.index:
        currentMax = min(Range , default=0)
        #value=round(df["Low"][i], 2)
        value=data['Close'][i]
        
            
        Range=Range[1:20]
        Range.append(value)
        daterange=daterange[1:20]
        daterange.append(i)
            
        if currentMax == min(Range , default=0):
            counter+=1
        else:
            counter = 0
        if counter ==  counter_lvl:
            lastPivot=currentMax
            dateloc =Range.index(lastPivot)
            lastDate = daterange[dateloc]
            pivots.append(lastPivot)
            dates.append(lastDate)
    print()
    #timeD = dt.timedelta(days=500)

    for index in range(1, len(pivots)):
        #print(str(pivots[index]) + " :" + str(dates[index]))
        line = pd.DataFrame({'Date':[dates[index]], 'price':[pivots[index]], 'Signal':[1]})
        signals = signals.append(line, ignore_index=True)
            
        #plt.plot_date([dates[index], dates[index] + timeD],
        #    [pivots[index], pivots[index]] , linestyle='solid' , linewidth=1, marker=',', color='red')

        if plotting == True:
            plt.plot_date([dates[index], dates[index]],
            [pivots[index], pivots[index]], marker='^', color='green')

    if plotting == True:
        plt.grid()
        plt.show()

    return signals